name: Update Blog Archive

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 * * * *'

jobs:
  update_blog_archive:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build and Run Blog Crawler
        run: |
          go build -o blog_crawler
          ./blog_crawler

      - name: Auto Commit and Push Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update xargin_blogs.md"
          branch: master
          file_pattern: xargin_blogs.md
          github_token: ${{ secrets.GH_TOKEN }}
